config/routes.rb
DBFruitVar::Application.routes.draw do
  
  post "select_collection/select"
  get "report_menu/index", as: :report_menu
  get "blocks/select", as: :blocks_select

  resources :blocks do
    resources :phenology_records
    resources :production_records
    member do
      get 'showphenology'
    end
  end 

  resources :phenology_records
  
  resources :production_records do
    collection do
      get 'report'
    end
  end

  
  resources :trees

  resources :accessions do
    collection do
      get 'report'
      get 'summary_report'
    end
  end

  resources :collections do
   collection do
      get 'report'
      get 'map'
    end
  end

  resources :groups

  resources :species

  resources :countries

  resources :locations

  root 'home#index'

end

app/models/collection.rb
class Collection < ActiveRecord::Base
  belongs_to :location
  belongs_to :species
  has_many :blocks

  self.per_page = 15

  def self.to_csv(options = {})
  	CSV.generate(options) do |csv|
   		csv << column_names
   		all.each do |collection|
  			csv << collection.attributes.values_at(*column_names)
   		end
 	  end
  end

  def self.filtered_by_collection(selected_collection)

    if selected_collection == "None"
      all
    else
      where("id = ?", selected_collection.to_i)
    end

  end

  
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: [:show, :edit, :update, :destroy]
 
  # GET /collections
  # GET /collections.json
  def index
    
    if params[:per_page]
      @per_page = params[:per_page]
    else
      @per_page = Collection.per_page 
    end
    
    @search = Collection.filtered_by_collection(session[:selected_collection]).ransack(params[:q])
    @collections = @search.result.paginate(:page => params[:page], :per_page => @per_page)

    respond_to do |format|
      format.html
      format.csv { send_data @search.result.to_csv }
      format.xls { send_data @search.result.to_csv(col_sep: "\t") }
      format.pdf do
        pdf = CollectionReport.new(@search.result)
        send_data pdf.render, filename: 'collections_report.pdf', type: 'application/pdf', disposition: 'inline'
      end 
    end


  end

  # GET /collections/1
  # GET /collections/1.json
  def show
  end

  # GET /collections/new
  def new
    @collection = Collection.new
  end

  # GET /collections/1/edit
  def edit
  end

  # POST /collections
  # POST /collections.json
  def create
    @collection = Collection.new(collection_params)

    respond_to do |format|
      if @collection.save
        format.html { redirect_to @collection, notice: 'Collection was successfully created.' }
        format.json { render action: 'show', status: :created, collection: @collection }
      else
        format.html { render action: 'new' }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collections/1
  # PATCH/PUT /collections/1.json
  def update
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to @collection, notice: 'Collection was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1
  # DELETE /collections/1.json
  def destroy
    @collection.destroy
    respond_to do |format|
      format.html { redirect_to collections_url }
      format.json { head :no_content }
    end
  end

  def report
  
    if params[:per_page]
      @per_page = params[:per_page]
    else
      @per_page = Location.per_page 
    end
    
    @search = Collection.filtered_by_collection(session[:selected_collection]).ransack(params[:q])
    @search.build_grouping unless @search.groupings.any?
    @collections = @search.result.paginate(:page => params[:page], :per_page => @per_page)
    #@search.build_condition

    @url_report = report_collections_path

    respond_to do |format|
      format.html
      format.js
      format.csv { send_data @search.result.to_csv }
      format.xls { send_data @search.result.to_csv(col_sep: "\t") }
      format.pdf do
        pdf = CollectionReport.new(@search.result)
        send_data pdf.render, filename: 'collections_report.pdf', type: 'application/pdf', disposition: 'inline'
      end 
    end

  end

  def map

    @search = Collection.filtered_by_collection(session[:selected_collection]).ransack(params[:q])
    @search.build_grouping unless @search.groupings.any?
    @collections = Collection.filtered_by_collection(session[:selected_collection])

    respond_to do |format|
     format.html
     format.json
     format.pdf do
        pdf = CollectionMapReport.new(@search.result)
        send_data pdf.render, filename: 'collections_map.pdf', type: 'application/pdf', disposition: 'inline'
      end 
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def collection_params
      params.require(:collection).permit(:name, :row_distance, :tree_distance, :location_id, :species_id)
    end

end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/_form.html.erb
<%= simple_form_for(@collection, html: {class: 'form-group'}, defaults: { input_html: { class: 'form-control'}} ) do |f| %>
 <% if @collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @collection.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :name %>
  <%= f.association :location %>
  <%= f.association :species %>
  <%= f.input :row_distance %>
  <%= f.input :tree_distance %>
  <p></p>
  <%= f.button :submit %>
   <p></p>
<% end %>

app/views/collections/edit.html.erb
<h3>Editing collection</h3>

<%= render 'form' %>

<%= link_to 'Show', @collection, :class => 'btn btn-xs btn-primary '  %> |
<%= link_to 'Back', collections_path, :class => 'btn btn-xs btn-primary '  %>

app/views/collections/index.html.erb
<div class='row'>
  <div class="col-md-9">
    <h4>Listing collections</h4>
  </div>
  <div class="col-md-3">
    <%= search_form_for @search, :html => {:class => "form-inline"} do |f| %> 
      <%= hidden_field_tag :per_page, @per_page %>
      <div class='form-group'>
        <div class='input-group'>
          <%= f.text_field  :name_cont, :placeholder => 'Name contains', :class => "form-control input-sm" %>
          <span class='input-group-btn'>
            <button class="btn btn-sm btn-default" type="submit"><span class="glyphicon glyphicon-search"></span></button>
          </span>
        </div>
      </div>
      
    <% end %>
  </div>
</div>

<div class='row'>
  <div class="col-md-9">
    <div>
      <%= label_tag 'selectnumber', 'Show' %>
      <%= select_tag :per_page, options_for_select([10,15,20,50], @per_page.to_i), :onchange => "if(this.value){window.location='?per_page='+this.value;}"%>
      <%= label_tag 'entries', 'entries' %>
    </div>
  </div>
  <div class="col-md-3">
    <%= link_to 'New collection', new_collection_path, :class => 'btn btn-xs btn-primary pull-right' %>
  </div>
</div>

<table class="table table-striped table-condensed ">
  <thead>
    <tr>
      <th><%= sort_link @search, :name, "Name" %></th>
      <th><%= sort_link @search, :location_id, "Location" %></th>
      <th><%= sort_link @search, :species_id, "Species" %></th>
      <th><%= sort_link @search, :row_distance, "Row distance" %></th>
      <th><%= sort_link @search, :tree_distance, "Tree distance" %></th>
      <th>
        <%= link_to collections_path(:q => params[:q], :qs => params[:qs], format: "csv"), class: "btn btn-xs btn-default" do %>
          <span class="glyphicon glyphicon-download"></span> CSV </i>
        <% end %>
      <th>
        <%= link_to collections_path(:q => params[:q], :qs => params[:qs], format: "xls"), class: "btn btn-xs btn-default" do %>
          <span class="glyphicon glyphicon-download"></span> XLS </i>
        <% end %>
      </th>
      <th>
        <%= link_to collections_path(:q => params[:q], :qs => params[:qs], format: "pdf"), class: "btn btn-xs btn-default" do %>
          <span class="glyphicon glyphicon-download"></span> PDF </i>
        <% end %>
      </th>
    </tr>
  </thead>

  <tbody>
    <% @collections.each do |collection| %>
      <tr>
        <td><%= collection.name %></td>
        <td><%= collection.location.name %></td>
        <td><%= collection.species.name %></td>
        <td><%= collection.row_distance %></td>
        <td><%= collection.tree_distance %></td>        
        <td><%= link_to 'Show', collection, :class => 'btn btn-xs btn-default ' %></td>
        <td><%= link_to 'Edit', edit_collection_path(collection), :class => 'btn btn-xs btn-primary ' %></td>
        <td><%= link_to 'Destroy', collection, :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-xs btn-danger ' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @collections, renderer: BootstrapPagination::Rails, class: 'pagination-sm' %>

app/views/collections/map.html.erb
<div class='row'>
  <div class="col-md-9">
    <h4>Map of collections </h4>
  </div>
  <div class="col-md-3">
    <%= search_form_for @search, :url => 'map', :html => {:class => "form-inline"} do |f| %> 
      <%= hidden_field_tag :per_page, @per_page %>
      <div class='form-group'>
        <div class='input-group'>
          <%= f.text_field  :location_name_cont, :placeholder => 'Location name contains', :class => "form-control input-sm" %>
          <span class='input-group-btn'>
            <button class="btn btn-sm btn-default" type="submit"><span class="glyphicon glyphicon-search"></span></button>
          </span>
        </div>
      </div> 
    <% end %>
  </div>
</div>
<div class='row'>
  <div class="col-md-9">
  </div>
  <div class="col-md-3">
    <%= link_to 'Advanced search', map_collections_path, {:class => 'btn btn-default btn-xs pull-right', :style =>'margin-bottom: 3px;', :remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-search-window'}  %>
  </br>
  </div>
</div>

<div class='row'>
  <div class="col-md-9">
  </div>
  <div class="col-md-3">
    <div class='pull-right'>
        <%= link_to map_collections_path(:q => params[:q], :qs => params[:qs], format: "pdf"), class: "btn btn-xs btn-default" do %>
          <span class="glyphicon glyphicon-download"></span> PDF </i>
        <% end %>
    </div>
  </div>
</div>

<div class="modal fade" id="modal-search-window" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
</div>

<div class='row'>
  <div class="google-map-canvas col-md-12" id="map-canvas">
  </div>
</div>

<script type="text/javascript">
     function initialize() {
        var mapOptions = {
          center: new google.maps.LatLng(42.1, 3.0),
          zoom: 12
        };
        var map = new google.maps.Map(document.getElementById("map-canvas"),
            mapOptions);

        $.getJSON("/collections/map.json", function(json) {
          if (json.length > 0) {
            for (i=0; i<json.length; i++) {
              var place = json[i];
              addLocation(place);
            }
          }
        });

        function addLocation(place) {
            var point = new google.maps.LatLng(place.latitude, place.longitude);

            var marker = new google.maps.Marker({
              position: point,
              title: place.name
            });

            // To add the marker to the map, call setMap();
            marker.setMap(map);
        }

      }

      google.maps.event.addDomListener(window, 'load', initialize);      
</script>

<style type="text/css">
      html { height: 100% }
      body { height: 100%; margin: 0; padding: 0 }
      #map-canvas { height: 500px; width: 100%; margin: 20px;}
</style>

app/views/collections/new.html.erb
<h3>New collection</h3>

<%= render 'form' %>

<%= link_to 'Back', collections_path, :class => 'btn btn-xs btn-primary '  %>

app/views/collections/report.html.erb
<div class='row'>
  <div class="col-md-9">
    <h4>Listing collections to report</h4>
  </div>
  <div class="col-md-3">
    <%= search_form_for @search, :url => 'report', :html => {:class => "form-inline"} do |f| %> 
      <%= hidden_field_tag :per_page, @per_page %>
      <div class='form-group'>
        <div class='input-group'>
          <%= f.text_field  :location_name_cont, :placeholder => 'Location name contains', :class => "form-control input-sm" %>
          <span class='input-group-btn'>
            <button class="btn btn-sm btn-default" type="submit"><span class="glyphicon glyphicon-search"></span></button>
          </span>
        </div>
      </div>
      
    <% end %>
  </div>
</div>
<div class='row'>
  <div class="col-md-9">
  </div>
  <div class="col-md-3">
    <%= link_to 'Advanced search', report_collections_path, {:class => 'btn btn-default btn-xs pull-right', :style =>'margin-bottom: 3px;', :remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-search-window'}  %>
  </br>
  </div>
</div>

<div class='row'>
  <div class="col-md-9">
    <div>
      <%= label_tag 'selectnumber', 'Show' %>
      <%= select_tag :per_page, options_for_select([10,15,20,50], @per_page.to_i), :onchange => "if(this.value){window.location='?per_page='+this.value;}"%>
      <%= label_tag 'entries', 'entries' %>
    </div>
  </div>
  <div class="col-md-3">
    <div class='pull-right'>
        <%= link_to report_collections_path(:q => params[:q], :qs => params[:qs], format: "csv"), class: "btn btn-xs btn-default" do %>
          <span class="glyphicon glyphicon-download"></span> CSV </i>
        <% end %>
        <%= link_to report_collections_path(:q => params[:q], :qs => params[:qs], format: "xls"), class: "btn btn-xs btn-default" do %>
          <span class="glyphicon glyphicon-download"></span> XLS </i>
        <% end %>
        <%= link_to report_collections_path(:q => params[:q], :qs => params[:qs], format: "pdf"), class: "btn btn-xs btn-default" do %>
          <span class="glyphicon glyphicon-download"></span> PDF </i>
        <% end %>
    </div>
  </div>
</div>


<div class="modal fade" id="modal-search-window" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
</div>

<table class="table table-striped table-condensed ">
  <thead>
    <tr>
      <th><%= sort_link @search, :name, "Name" %></th>
      <th><%= sort_link @search, :location_id, "Location" %></th>
      <th><%= sort_link @search, :species_id, "Species" %></th>
      <th><%= sort_link @search, :row_distance, "Row distance" %></th>
      <th><%= sort_link @search, :tree_distance, "Tree distance" %></th>
    </tr>
  </thead>

  <tbody>
    <% @collections.each do |collection| %>
      <tr>
        <td><%= collection.name %></td>
        <td><%= collection.location.name %></td>
        <td><%= collection.species.name %></td>
        <td><%= collection.row_distance %></td>
        <td><%= collection.tree_distance %></td>        
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @collections, renderer: BootstrapPagination::Rails, class: 'pagination-sm' %>

app/views/collections/report.js.erb
$("#modal-search-window").html("<%= escape_javascript(render partial: "advanced_search", locals: {url_report: @url_report}) %>");

app/views/collections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @collection.name %>
</p>

<p>
  <strong>Row distance:</strong>
  <%= @collection.row_distance %>
</p>

<p>
  <strong>Tree distance:</strong>
  <%= @collection.tree_distance %>
</p>

<p>
  <strong>Location:</strong>
  <%= @collection.location.name %>
</p>

<p>
  <strong>Species:</strong>
  <%= @collection.species.name %>
</p>

<%= link_to 'Edit', edit_collection_path(@collection), :class => 'btn btn-xs btn-primary '  %> |
<%= link_to 'Back', collections_path, :class => 'btn btn-xs btn-primary '  %>