config/routes.rb
DBFruitVar::Application.routes.draw do
  
  post "select_collection/select"
  get "report_menu/index", as: :report_menu
  get "blocks/select", as: :blocks_select

  resources :blocks do
    resources :phenology_records
    resources :production_records
    member do
      get 'showphenology'
    end
  end 

  resources :phenology_records
  
  resources :production_records do
    collection do
      get 'report'
    end
  end

  
  resources :trees

  resources :accessions do
    collection do
      get 'report'
      get 'summary_report'
    end
  end

  resources :collections do
   collection do
      get 'report'
      get 'map'
    end
  end

  resources :groups

  resources :species

  resources :countries

  resources :locations

  root 'home#index'

end

app/models/phenology_record.rb
class PhenologyRecord < ActiveRecord::Base
  belongs_to :block

  self.per_page = 15


	def self.to_csv(options = {})
  		CSV.generate(options) do |csv|
    		csv << column_names
    		all.each do |phenology_record|
      			csv << phenology_record.attributes.values_at(*column_names)
    		end
 		end
	end

end

app/controllers/phenology_records_controller.rb
class PhenologyRecordsController < ApplicationController
  before_action :set_phenology_record, only: [:show, :edit, :update, :destroy]
  before_filter :load_block
  
  # GET /phenology_records
  # GET /phenology_records.json
  def index
    if params[:per_page]
      @per_page = params[:per_page]
    else
      @per_page = Location.per_page 
    end
    
    @search = PhenologyRecord.ransack(params[:q])
    @phenology_records = @search.result.paginate(:page => params[:page], :per_page => @per_page)

    respond_to do |format|
      format.html
      format.csv { send_data @search.result.to_csv }
      format.xls { send_data @search.result.to_csv(col_sep: "\t") }
      format.pdf do
        pdf = PhenoologyRecordReport.new(@search.result)
        send_data pdf.render, filename: 'phenology_records_report.pdf', type: 'application/pdf', disposition: 'inline'
      end 
    end

  end

  # GET /phenology_records/1
  # GET /phenology_records/1.json
  def show
   @phenology_record = @block.phenology_records.find(params[:id])
  end

  # GET /phenology_records/new
  def new
    @phenology_record = @block.phenology_records.new
    @phenology_record.block_id = @block.id
  end

   # GET /phenology_records/1/edit
  def edit
    @phenology_record = @block.phenology_records.find(params[:id])
  end
  
  # POST /phenology_records
  # POST /phenology_records.json
  def create

    @phenology_record = @block.phenology_records.new(phenology_record_params)
    

    respond_to do |format|
      if @phenology_record.save
        format.html { redirect_to [@block, @phenology_record], notice: 'Phenology record was successfully created.' }
        format.json { render action: 'show', status: :created, location: @phenology_record }
      else
        format.html { render action: 'new' }
        format.json { render json: @phenology_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phenology_records/1
  # PATCH/PUT /phenology_records/1.json
  def update

    @phenology_record = @block.phenology_records.find(params[:id])

    respond_to do |format|
      if @phenology_record.update(phenology_record_params)
        format.html { redirect_to [@block, @phenology_record], notice: 'Phenology record was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @phenology_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phenology_records/1
  # DELETE /phenology_records/1.json
  def destroy
    @phenology_record = @block.phenology_records.find(params[:id])
    @phenology_record.destroy
    respond_to do |format|
      format.html { redirect_to showphenology_block_path(@block) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phenology_record
      @phenology_record = PhenologyRecord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def phenology_record_params
      params.require(:phenology_record).permit(:year, :c3, :e2, :f2, :g, :block_id)
    end
   
    def load_block
      @block = Block.find(params[:block_id])
    end
end

app/helpers/phenology_records_helper.rb
module PhenologyRecordsHelper
end

app/views/phenology_records/_form.html.erb
<%= simple_form_for([@block, @phenology_record], html: {class: 'form-group'}, defaults: { input_html: { class: 'form-control'}} ) do |f| %>
  <% if @phenology_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@phenology_record.errors.count, "error") %> prohibited this location from being saved:</h2>
      <ul>
      <% @phenology_record.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.association :block, :label_method => lambda { |r| "#{r.collection.name} #{r.accession.name} #{r.row}/#{r.first_tree}-#{r.last_tree} " }, value_method: :id, include_blank: false %>
    <%= f.input :year, :input_html => { data: {behaviour: "datepicker"}}, :as => :string  %>
    <%= f.input :c3, :input_html => { data: {behaviour: "datepicker"}}, :as => :string  %>
    <%= f.input :e2, :input_html => { data: {behaviour: "datepicker"}}, :as => :string  %>
    <%= f.input :f2, :input_html => { data: {behaviour: "datepicker"}}, :as => :string  %>
    <%= f.input :g, :input_html => { data: {behaviour: "datepicker"}}, :as => :string  %>
    
  
    <p></p>
    <%= f.button :submit %>
    <p></p>

<% end %>

app/views/phenology_records/edit.html.erb
<h1>Editing phenology record</h1>

<%= render 'form' %>

<%= link_to 'Show', [@block, @phenology_record], :class => 'btn btn-xs btn-primary ' %> |
<%= link_to 'Back', showphenology_block_path(@block), :class => 'btn btn-xs btn-primary ' %>
 

app/views/phenology_records/index.html.erb
<div class='row'>
  <div class="col-md-9">
    <h4>Listing phenology records</h4>
  </div>
  <div class="col-md-3">
    <%= search_form_for @search, :html => {:class => "form-inline"} do |f| %> 
      <%= hidden_field_tag :per_page, @per_page %>
      <div class='form-group'>
        <div class='input-group'>
          <%= f.text_field  :block_accession_name_cont, :placeholder => 'Name contains', :class => "form-control input-sm" %>
          <span class='input-group-btn'>
            <button class="btn btn-sm btn-default" type="submit"><span class="glyphicon glyphicon-search"></span></button>
          </span>
        </div>
      </div>
      
    <% end %>
  </div>
</div>

<div class='row'>
  <div class="col-md-9">
    <div>
      <%= label_tag 'selectnumber', 'Show' %>
      <%= select_tag :per_page, options_for_select([10,15,20,50], @per_page.to_i), :onchange => "if(this.value){window.location='?per_page='+this.value;}"%>
      <%= label_tag 'entries', 'entries' %>
    </div>
  </div>
  <div class="col-md-3">
    <%= link_to 'New phenology record', new_phenology_record_path, :class => 'btn btn-xs btn-primary pull-right' %>
  </div>
</div>

<table class="table table-striped table-condensed ">
  <thead>
    <tr>
      <th><%= sort_link @search, :year, "Year" %></th>
      <th><%= sort_link @search, :c3, "C3" %></th>
      <th><%= sort_link @search, :e2, "E2" %></th>
      <th><%= sort_link @search, :f2, "F2" %></th>
      <th><%= sort_link @search, :g, "G" %></th>
      <th>
        <%= link_to phenology_records_path(:q => params[:q], :qs => params[:qs], format: "csv"), class: "btn btn-xs btn-default" do %>
          <span class="glyphicon glyphicon-download"></span> CSV </i>
        <% end %>
      <th>
        <%= link_to phenology_records_path(:q => params[:q], :qs => params[:qs], format: "xls"), class: "btn btn-xs btn-default" do %>
          <span class="glyphicon glyphicon-download"></span> XLS </i>
        <% end %>
      </th>
      <th>
        <%= link_to phenology_records_path(:q => params[:q], :qs => params[:qs], format: "pdf"), class: "btn btn-xs btn-default" do %>
          <span class="glyphicon glyphicon-download"></span> PDF </i>
        <% end %>
      </th>
    </tr>
  </thead>

  <tbody>
    <% @phenology_records.each do |phenology_record| %>
      <tr>
        <td><%= phenology_record.year %></td>
        <td><%= phenology_record.c3 %></td>
        <td><%= phenology_record.e2 %></td>
        <td><%= phenology_record.f2 %></td>
        <td><%= phenology_record.g %></td>
        <td><%= phenology_record.block %></td>
        <td><%= link_to 'Show', phenology_record,  :class => 'btn btn-xs btn-default ' %></td>
        <td><%= link_to 'Edit', edit_phenology_record_path(phenology_record) , :class => 'btn btn-xs btn-primary '  %></td>
        <td><%= link_to 'Destroy', phenology_record, :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-xs btn-danger ' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @accessions, renderer: BootstrapPagination::Rails, class: 'pagination-sm' %>

app/views/phenology_records/new.html.erb
<h1>New phenology record</h1>

<%= render 'form' %>

<%= link_to 'Back', showphenology_block_path(@block), :class => 'btn btn-xs btn-primary ' %>

app/views/phenology_records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Year:</strong>
  <%= @phenology_record.year %>
</p>

<p>
  <strong>C3:</strong>
  <%= @phenology_record.c3 %>
</p>

<p>
  <strong>E2:</strong>
  <%= @phenology_record.e2 %>
</p>

<p>
  <strong>F2:</strong>
  <%= @phenology_record.f2 %>
</p>

<p>
  <strong>G:</strong>
  <%= @phenology_record.g %>
</p>

<p>
  <strong>Block:</strong>
  <%= @phenology_record.block %>
</p>

<%= link_to 'Edit', edit_block_phenology_record_path(@block, @phenology_record), :class => 'btn btn-xs btn-primary ' %> |
<%= link_to 'Back', showphenology_block_path(@block), :class => 'btn btn-xs btn-primary ' %>