config/routes.rb
DBFruitVar::Application.routes.draw do
  
  post "select_collection/select"
  get "report_menu/index", as: :report_menu
  get "blocks/select", as: :blocks_select

  resources :blocks do
    resources :phenology_records
    resources :production_records
    member do
      get 'showphenology'
    end
  end 

  resources :phenology_records
  
  resources :production_records do
    collection do
      get 'report'
    end
  end

  
  resources :trees

  resources :accessions do
    collection do
      get 'report'
      get 'summary_report'
    end
  end

  resources :collections do
   collection do
      get 'report'
      get 'map'
    end
  end

  resources :groups

  resources :species

  resources :countries

  resources :locations

  root 'home#index'

end

app/models/tree.rb
class Tree < ActiveRecord::Base
  
  	belongs_to :block

    self.per_page = 15

  	def self.to_csv(options = {})
  		CSV.generate(options) do |csv|
    		csv << column_names
    		all.each do |tree|
      			csv << tree.attributes.values_at(*column_names)
    		end
      end
 		end
  	
end

app/controllers/trees_controller.rb
class TreesController < ApplicationController
  before_action :set_tree, only: [:show, :edit, :update, :destroy]
  
  # GET /trees
  # GET /trees.json
  def index
   
    if params[:per_page]
      @per_page = params[:per_page]
    else
      @per_page = Tree.per_page 
    end
    
    @search = Tree.ransack(params[:q])
    @trees = @search.result.paginate(:page => params[:page], :per_page => @per_page)

    respond_to do |format|
      format.html
      format.csv { send_data @search.result.to_csv }
      format.xls { send_data @search.result.to_csv(col_sep: "\t") }
      format.pdf do
        pdf = TreeReport.new(@search.result)
        send_data pdf.render, filename: 'trees_report.pdf', type: 'application/pdf', disposition: 'inline'
      end 
    end

  end

  # GET /trees/1
  # GET /trees/1.json
  def show
  end

  # GET /trees/new
  def new
    @tree = Tree.new
  end

  # GET /trees/1/edit
  def edit
  end

  # POST /trees
  # POST /trees.json
  def create
    @tree = Tree.new(tree_params)

    respond_to do |format|
      if @tree.save
        format.html { redirect_to @tree, notice: 'Tree was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tree }
      else
        format.html { render action: 'new' }
        format.json { render json: @tree.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trees/1
  # PATCH/PUT /trees/1.json
  def update
    respond_to do |format|
      if @tree.update(tree_params)
        format.html { redirect_to @tree, notice: 'Tree was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tree.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trees/1
  # DELETE /trees/1.json
  def destroy
    @tree.destroy
    respond_to do |format|
      format.html { redirect_to trees_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tree
      @tree = Tree.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tree_params
      params.require(:tree).permit(:tree, :row, :planting_date, :pullout_date, :rootstock, :oldcode, :oldaccessioncode, :oldcollectioncode, :block_id)
    end

end

app/helpers/trees_helper.rb
module TreesHelper
end

app/views/trees/_form.html.erb
<%= simple_form_for(@tree, html: {class: 'form-group'}, defaults: { input_html: { class: 'form-control'}}) do |f| %>
  
  <% if @tree.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @tree.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
    <%= f.association :block %>
    <%= f.input :tree %>
    <%= f.input :row %>
    <%= f.input :planting_date, :input_html => { data: {behaviour: "datepicker"}}, :as => :string %>     
    <%= f.input :pullout_date, :input_html => { data: {behaviour: "datepicker"}}, :as => :string %>      
    <%= f.input :rootstock %> 
    <p></p> 
    <%= f.button :submit %>
    <p></p>
<% end %>

app/views/trees/edit.html.erb
<h3>Editing tree</h3>

<%= render 'form' %>

<%= link_to 'Show', @tree, :class => 'btn btn-xs btn-primary '%> |
<%= link_to 'Back', trees_path, :class => 'btn btn-xs btn-primary ' %>

app/views/trees/index.html.erb
<div class='row'>
  <div class="col-md-9">
    <h4>Listing trees</h4>
  </div>
  <div class="col-md-3">
    <%= search_form_for @search, :html => {:class => "form-inline"} do |f| %> 
      <%= hidden_field_tag :per_page, @per_page %>
      <div class='form-group'>
        <div class='input-group'>
          <%= f.text_field  :block_accession_name_cont, :placeholder => 'Name contains', :class => "form-control input-sm" %>
          <span class='input-group-btn'>
            <button class="btn btn-sm btn-default" type="submit"><span class="glyphicon glyphicon-search"></span></button>
          </span>
        </div>
      </div>
      
    <% end %>
  </div>
</div>

<div class='row'>
  <div class="col-md-9">
    <div>
      <%= label_tag 'selectnumber', 'Show' %>
      <%= select_tag :per_page, options_for_select([10,15,20,50], @per_page.to_i), :onchange => "if(this.value){window.location='?per_page='+this.value;}"%>
      <%= label_tag 'entries', 'entries' %>
    </div>
  </div>
  <div class="col-md-3">
    <%= link_to 'New tree', new_tree_path, :class => 'btn btn-xs btn-primary pull-right' %>
  </div>
</div>

<table class="table table-striped table-condensed ">
  <thead>
    <tr>
      <th><%= sort_link @search, :block_id, "Block" %></th>
      <th><%= sort_link @search, :tree, "Tree" %></th>
      <th><%= sort_link @search, :row, "Row" %></th>
      <th><%= sort_link @search, :planting_date, "Planting date" %></th>
      <th><%= sort_link @search, :pullout_date, "Pullout date" %></th>
      <th><%= sort_link @search, :rootstock, "Rootstock" %></th>
       <th>
        <%= link_to trees_path(:q => params[:q], :qs => params[:qs], format: "csv"), class: "btn btn-xs btn-default" do %>
          <span class="glyphicon glyphicon-download"></span> CSV </i>
        <% end %>
      <th>
        <%= link_to trees_path(:q => params[:q], :qs => params[:qs], format: "xls"), class: "btn btn-xs btn-default" do %>
          <span class="glyphicon glyphicon-download"></span> XLS </i>
        <% end %>
      </th>
      <th>
        <%= link_to trees_path(:q => params[:q], :qs => params[:qs], format: "pdf"), class: "btn btn-xs btn-default" do %>
          <span class="glyphicon glyphicon-download"></span> PDF </i>
        <% end %>
      </th>
    </tr>
  </thead>

  <tbody>
    <% @trees.each do |tree| %>
      <tr>
        <td><%= tree.block.id %></td>
        <td><%= tree.tree %></td>
        <td><%= tree.row %></td>
        <td><%= tree.planting_date %></td>
        <td><%= tree.pullout_date %></td>
        <td><%= tree.rootstock %></td>
        <td><%= link_to 'Show', tree,  :class => 'btn btn-xs btn-default '  %></td>
        <td><%= link_to 'Edit', edit_tree_path(tree), :class => 'btn btn-xs btn-primary '   %></td>
        <td><%= link_to 'Destroy', tree, :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-xs btn-danger ' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @trees, renderer: BootstrapPagination::Rails, class: 'pagination-sm' %>

app/views/trees/new.html.erb
<h3>New tree</h3>

<%= render 'form' %>

<%= link_to 'Back', trees_path, :class => 'btn btn-xs btn-primary '%>

app/views/trees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tree:</strong>
  <%= @tree.tree %>
</p>

<p>
  <strong>Row:</strong>
  <%= @tree.row %>
</p>

<p>
  <strong>Planting date:</strong>
  <%= @tree.planting_date %>
</p>

<p>
  <strong>Pullout date:</strong>
  <%= @tree.pullout_date %>
</p>

<p>
  <strong>Rootstock:</strong>
  <%= @tree.rootstock %>
</p>

<p>
  <strong>Oldcode:</strong>
  <%= @tree.oldcode %>
</p>

<p>
  <strong>Oldaccessioncode:</strong>
  <%= @tree.oldaccessioncode %>
</p>

<p>
  <strong>Oldcollectioncode:</strong>
  <%= @tree.oldcollectioncode %>
</p>

<p>
  <strong>Block:</strong>
  <%= @tree.block %>
</p>

<%= link_to 'Edit', edit_tree_path(@tree), :class => 'btn btn-xs btn-primary '%> |
<%= link_to 'Back', trees_path, :class => 'btn btn-xs btn-primary ' %>